//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3082
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Modules.Store.WebControls {
    
    
    /// <summary>
    /// Classe ProductList.
    /// </summary>
    /// <remarks>
    /// Classe générée automatiquement.
    /// </remarks>
    public partial class ProductList {
    }
}
