//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3615
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Modules.Store.WebControls {
    
    
    /// <summary>
    /// Classe CartDetail.
    /// </summary>
    /// <remarks>
    /// Classe générée automatiquement.
    /// </remarks>
    public partial class CartDetail {
        
        /// <summary>
        /// Contrôle lblCartEmpty.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCartEmpty;
        
        /// <summary>
        /// Contrôle grdItems.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataGrid grdItems;
        
        /// <summary>
        /// Contrôle valSummaryCart.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary valSummaryCart;
    }
}
