//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3615
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Modules.Store.WebControls {
    
    
    /// <summary>
    /// Classe CustomerAdmin.
    /// </summary>
    /// <remarks>
    /// Classe générée automatiquement.
    /// </remarks>
    public partial class CustomerAdmin {
        
        /// <summary>
        /// Contrôle lblOrderNumber.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblOrderNumber;
        
        /// <summary>
        /// Contrôle tbOrderNumber.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox tbOrderNumber;
        
        /// <summary>
        /// Contrôle btnSearch.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
        /// <summary>
        /// Contrôle lblCustomers.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblCustomers;
        
        /// <summary>
        /// Contrôle lstCustomers.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList lstCustomers;
        
        /// <summary>
        /// Contrôle lblOrderStatus.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblOrderStatus;
        
        /// <summary>
        /// Contrôle lstOrderStatus.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList lstOrderStatus;
        
        /// <summary>
        /// Contrôle noOrdersFound.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label noOrdersFound;
        
        /// <summary>
        /// Contrôle plhOrders.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder plhOrders;
    }
}
