//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3615
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Modules.Store.Providers.Tax.DefaultTaxProvider {
    
    
    /// <summary>
    /// Classe DefaultTaxAdmin.
    /// </summary>
    /// <remarks>
    /// Classe générée automatiquement.
    /// </remarks>
    public partial class DefaultTaxAdmin {
        
        /// <summary>
        /// Contrôle lblEnableTax.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblEnableTax;
        
        /// <summary>
        /// Contrôle cbEnableTax.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbEnableTax;
        
        /// <summary>
        /// Contrôle lblTaxRate.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblTaxRate;
        
        /// <summary>
        /// Contrôle txtTaxRate.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTaxRate;
        
        /// <summary>
        /// Contrôle lblError.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblError;
        
        /// <summary>
        /// Contrôle btnSaveTaxRates.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnSaveTaxRates;
    }
}
